"""Write self-contained functions while preserving user-authored definitions."""

import ast
import keyword
import os
import symtable
import tempfile
from pathlib import Path

_GENERATED_MARKER = "# Generated by Augplot. Review before running on new data."


def write_python_function(
    code: str, path: str | Path, function_name: str, *, backend="auto"
) -> Path:
    if (
        not function_name.isidentifier()
        or keyword.iskeyword(function_name)
        or function_name.startswith("_")
    ):
        raise ValueError("function_name must be a public Python identifier.")
    target = Path(path)
    if target.suffix != ".py":
        raise ValueError("Python output path must end in .py.")
    if target.is_symlink():
        raise ValueError("Refusing to replace a symlink; use a regular Python file.")
    existing = target.read_text(encoding="utf-8") if target.exists() else ""
    try:
        existing_tree = ast.parse(existing)
        symbols = symtable.symtable(existing, str(target), "exec")
    except SyntaxError:
        raise ValueError(
            "Existing Python module is not valid Python; it was not changed."
        ) from None
    replacement = None
    if function_name in symbols.get_identifiers():
        for node in existing_tree.body:
            is_matching_function = isinstance(
                node, (ast.FunctionDef, ast.AsyncFunctionDef)
            ) and node.name == function_name
            if is_matching_function:
                marker_index = node.lineno - 2
                lines = existing.splitlines(keepends=True)
                if marker_index >= 0 and lines[marker_index].rstrip("\r\n") == _GENERATED_MARKER:
                    replacement = (marker_index, node.end_lineno)
                break
        if replacement is None:
            raise ValueError(
                f"Name {function_name!r} already exists and was not generated by Augplot; "
                "choose a different function_name."
            )
    tree = ast.parse(code)
    tree.body[0].name = function_name
    if backend != "plotly":
        # Reproduce the runtime style contexts in standalone source, without Augplot.
        preamble = "import matplotlib as augplot_mpl\n"
        context = "augplot_mpl.rc_context()"
        if backend in ("auto", "seaborn"):
            preamble += "import seaborn as augplot_sns\n"
            context += (
                ", augplot_sns.axes_style('whitegrid'), augplot_sns.plotting_context('notebook')"
            )
        wrapper = ast.parse(preamble + f"with {context}:\n    pass\n").body
        wrapper[-1].body = tree.body[0].body
        tree.body[0].body = wrapper
        ast.fix_missing_locations(tree)
    source = ast.unparse(tree) + "\n"
    generated = _GENERATED_MARKER + "\n" + source
    if replacement is None:
        content = existing.rstrip() + "\n\n\n" if existing.strip() else ""
        content += generated
    else:
        lines = existing.splitlines(keepends=True)
        start, end = replacement
        content = "".join(lines[:start]) + generated + "".join(lines[end:])
    # Verify the entire module before touching the destination.
    compile(content, str(target), "exec")
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=target.parent,
            prefix=".augplot-",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary = Path(handle.name)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if target.exists():
            temporary.chmod(target.stat().st_mode & 0o777)
        os.replace(temporary, target)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
    if target.stem.isidentifier() and not keyword.iskeyword(target.stem):
        print(
            f"# With {str(target.parent)!r} on your Python import path:\n"
            f"from {target.stem} import {function_name}\n"
            f"fig = {function_name}(your_data)\nfig"
        )
    else:
        print(f"Saved {function_name} to {target}. Use a valid module filename for direct imports.")
    return target
